on:
  push:
    # delete this item if you don't want to trigger this workflow when modify this repo
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 20:00 -> CST (China) 4:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 20 * * *'
  pull_request:
    branches: master
    
name: Mirror GitHub Selected Repos to Gitee
jobs:
  run:
    name: Sync-Gitee-Manual-and-Personal
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the sigminer repos to Gitee.
      uses: xgfd3/hub-mirror-action-with-china-source@master
      with:
        src: github/xgfd3
        dst: gitee/xgfd3
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        white_list: "sync2gitee"
        static_list: "sync2gitee"
        account_type: user
        force_update: true
